server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#    vault:
#      uri: http://localhost:8200
#      host: localhost
#      port: 8200
#      authentication: token
#      kv:
#        enabled: true
#      token: hvs.7vKKGJQTgjxRYalTmHVXnZjj
#
#  config:
#    import: vault://




  #      redis-rate-limiter:
  #        burst-capacity-header:
  #      routes:
  #        - id: gateway-service
  #          uri: http://localhost:8081/
  #          predicates:
  #            - Path=/api/auth/**
  #          filters:
  #            - AddRequestHeader=fist-request, first-request-header


  data:
    mongodb:
      uri: mongodb+srv://quangnam130520:Z72BGxu7D8VmvHKq@cluster0.fwoaemp.mongodb.net/?retryWrites=true&w=majority
      database: gateway

  redis:
    host: localhost
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
        time-between-eviction-runs: 10000
        max-wait: 10000

# Property for Spring Boot Actuator
#management:
#  endpoint:
#    env:
#      post:
#        enabled: true



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
jwt:
  secret: jwtsecret