#server:
#  port: 8080
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: gateway-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - AddRequestHeader=fist-request, first-request-header